# Netlify configuration file

# Production context (main branch)
[build]
  command = "npm run migrate && turbo build --filter=web"
  publish = "apps/web/.next"

# Staging context (staging branch)
[context.staging]
  command = "npm run migrate && turbo build --filter=web"
  publish = "apps/web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
