import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { createClient } from '@/lib/supabase/server'; // Import server-side Supabase client

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  let creditBalance = 0;

  if (user) {
    const { data, error } = await supabase
      .from('user_credits') // Assuming 'user_credits' table
      .select('amount')
      .eq('user_id', user.id)
      .single();

    if (error) {
      console.error('Error fetching credit balance in layout:', error);
    } else if (data) {
      creditBalance = data.amount;
    }
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        {user && (
          <div style={{ padding: '10px', textAlign: 'right', background: '#f0f0f0' }}>
            Credits: {creditBalance}
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
